# -*- coding: utf-8 -*-
"""Stock-Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UzILuOte4iZ43W57Jt6q0D3mgHq-fm_-
"""

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt


def get_stock_prices(stock_symbol):
    stock_data = yf.download(stock_symbol, start='2020-01-01', end='2022-12-31', progress=False)
    return stock_data


stock_symbol = "AAPL"  
price_data = get_stock_prices(stock_symbol)


df = pd.DataFrame(price_data)

plt.figure(figsize=(10, 5))
plt.plot(df["Close"])
plt.xlabel("Date")
plt.ylabel("Close Price")
plt.title(f"{stock_symbol} Stock Price")
plt.show()